name: main-stack
runtime:
  name: python
  options:
    virtualenv: venv
description: A Python program to deploy a Helm chart onto a Kubernetes cluster
config:
  pulumi:tags:
    value:
      pulumi:template: ""
